In [1]:
import numpy as np

one_vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(one_vector)


[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
zero_matrix = np.zeros((3, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
matrix_5_5 = np.random.randint(1, 10, size=(5, 5))
print(matrix_5_5)

[[7 9 3 9 4]
 [9 6 5 5 6]
 [1 9 9 8 1]
 [7 8 1 1 4]
 [7 1 7 2 5]]


In [6]:
one_ONE_vector = np.random.randint(1, 10, size=(5,))

two_TWO_vector = np.random.randint(1, 10, size=(5,))

print(one_ONE_vector + two_TWO_vector)
print(one_ONE_vector - two_TWO_vector)
print(one_ONE_vector * two_TWO_vector)

[6 9 5 9 8]
[-4  5 -3 -1 -4]
[ 5 14  4 20 12]


In [7]:
vector_7_size = np.random.randint(1, 10, size=(7,))
vector_size_two = np.random.randint(1, 10, size=(7,))
scalar = np.dot(vector_7_size, vector_size_two)
print(scalar)


165


In [8]:
one_ONE_matrix = np.random.randint(1, 10, size=(2, 2))
two_TWO_matrix = np.random.randint(1, 10, size=(2, 3))
dobutok = np.dot(one_ONE_matrix, two_TWO_matrix)
print(dobutok)

[[68 56 76]
 [55 52 65]]


In [9]:
matrix_3_3 = np.random.randint(1, 10, size=(3, 3))
obernen = np.linalg.inv(matrix_3_3)
print(matrix_3_3)


[[5 8 5]
 [6 4 8]
 [4 2 9]]


In [10]:
matrix_4_four = np.random.random(size=(4, 4))
transp_matrix = matrix_4_four.T
print(transp_matrix)


[[0.90020653 0.62575806 0.31750387 0.77535876]
 [0.76593198 0.72956652 0.08566124 0.89376591]
 [0.0767628  0.63463296 0.52316569 0.01113984]
 [0.314503   0.02687513 0.70457852 0.38786341]]


In [16]:
matrix_3_4 = np.random.randint(1, 10, size=(3, 4))
vec_4_size = np.random.randint(1, 10, size=(4,))
dob_of_mat_and_vec = np.dot(matrix_3_4, vec_4_size)
print(dob_of_mat_and_vec)

[122 110 178]


In [15]:
matrix_2_on_three = np.random.random(size=(2, 3))
vec_3_size = np.random.random(size=(3,))
dob_of_mat_and_vec_2 = np.dot(matrix_2_on_three, vec_3_size)
print(dob_of_mat_and_vec)


[ 47  78 113]


In [14]:

matrix_2_on_two_a = np.random.randint(1, 10, size=(2, 2))
matrix_2_on_two_b = np.random.randint(1, 10, size=(2, 2))
print(matrix_2_on_two_a * matrix_2_on_two_b)

[[81 18]
 [16  2]]


In [17]:
matrix_2_on_two_с = np.random.randint(1, 10, size=(2, 2))
matrix_2_on_two_d = np.random.randint(1, 10, size=(2, 2))
dobutok = np.dot(matrix_2_on_two_с, matrix_2_on_two_d)
print(dobutok)

[[52 43]
 [68 59]]


In [18]:
matrix_100_el = np.random.randint(1, 100, size=(5, 5))
mat_sum = np.sum(matrix_100_el)
print(mat_sum)


1092


In [19]:
matrix_4_on_four_f = np.random.randint(1, 10, size=(4, 4))
matrix_4_on_four_g = np.random.randint(1, 10, size=(4, 4))
riznytsa = matrix_4_on_four_f - matrix_4_on_four_g
print(riznytsa)


[[ 0 -8  2 -1]
 [ 4  0  0  0]
 [ 2  1 -1  8]
 [ 0  0  1 -1]]


In [20]:
matrix_3_3_e = np.random.random(size=(3, 3))
sum_vec_of_matrix = np.sum(matrix_3_3_e,axis=1)
print(sum_vec_of_matrix)

[1.08003478 1.21849906 1.69712884]


In [21]:
matrix_3_3_р = np.random.randint(1,10,size=(3, 4))
square_matrix_sum = matrix_3_3_р ** 2
print(square_matrix_sum)


[[ 1  4 64 36]
 [25 16 16 81]
 [49 25 16 25]]


In [22]:

vec_1 = np.random.randint(1,51,size=(4,))
vec_2_x = np.sqrt(vec_1)
print(vec_2_x)


[3.60555128 3.87298335 6.40312424 6.164414  ]
